routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Contracts\Auth\Factory as AuthFactory;
use Illuminate\Support\Facades\Hash;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(
    ['prefix' => LaravelLocalization::setLocale(),
     'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {
        Route::get('/', function()
        {
            return view('welcome');
        });
        Route::prefix('/admin')->attribute('namespace', 'Admin')->group(function(){
            Route::get('/', 'HomeController@index')->name('admin.home.index');
            Route::resource('products', 'ProductController', ['as' => 'admin']);    
            Route::resource('orders', 'OrdersController', ['as' => 'admin']);    
            Route::resource('branches', 'BranchesController', ['as' => 'admin']);    
            Route::resource('users', 'UserController', ['as' => 'admin']);    
            Route::resource('payments', 'PaymentsController', ['as' => 'admin']);    
        });
        Route::get('/test' , function(){
            $credentials  = ['phone'=>'+1-386-764-6166','password'=>'123456789'];
           // dd(auth('api'));
            $user = auth('api')->attempt($credentials);
            dd($user);
        });
        
        

});

resources/views/admin/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ trans('dashboard') }}</title>

        <!--favicon -->
        <link rel="icon" href="/favicon.ico" type="image/x-icon"/>

        <!--app.css css-->
        <link rel="stylesheet" href="{{ url('assets/css/admin.app.css') }}">

        @if(app()->getLocale() == 'ar')
        <link rel="stylesheet" href="{{ url('assets/css/admin.app.rtl.css') }}">
        @endif

    </head>

    <body class="app ">

        <!--Header Style -->
        <div class="wave -three"></div>

        <!--loader -->
        <div id="spinner"></div>

        <!--app open-->
        <div id="app" class="page">
            <div class="main-wrapper" >

                <!--nav open-->
                <nav class="navbar navbar-expand-lg main-navbar">
                    {{-- <a class="header-brand" href="{{ route('admin.home.index') }}"> --}}
                        <img src="{{ url('assets/img/Icons/logo.png') }}" class="header-brand-img" alt="Splite-Admin  logo">
                    </a>
                    <form class="form-inline mr-auto">
                        <ul class="navbar-nav mr-2">
                            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link toggle"><i class="fa fa-reorder"></i></a></li>
                            <li><a href="#" data-toggle="search" class="nav-link nav-link d-md-none navsearch"><i class="fa fa-search"></i></a></li>
                        </ul>
                        {{--<div class="search-element mr-3">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                        <span class="Search-icon"><i class="fa fa-search"></i></span>
                        </div>--}}
                    </form>
                    <ul class="navbar-nav nav bar-right">
                        <li class="dropdown dropdown-list-toggle d-none d-lg-block ">
                            <a href="#" data-toggle="dropdown" class="nav-link  nav-link-lg "><i class=" fa fa-flag-o "></i></a>
                            <div class="dropdown-menu dropdown-menu-lg  dropdown-menu-right">
                                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                                    @if ($localeCode != App::getLocale())
                                        <a  href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" class="dropdown-item d-flex align-items-center">
                                            <div>
                                                <strong>{{$properties['native']}}</strong>
                                            </div>
                                        </a>
                                    @endif 
                                @endforeach
                            </div>
                        </li>

                        <li class="dropdown dropdown-list-toggle d-none d-lg-block">
                            <a href="#" class="nav-link nav-link-lg full-screen-link">
                                <i class="fa fa-expand " id="fullscreen-button"></i>
                            </a>
                        </li>
                        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg d-flex">
                                <span class="mr-3 mt-2 d-none d-lg-block ">
                                    {{-- <span class="text-white">{{trans('hello')}},<span class="ml-1">{{auth()->user()->name}}</span></span> --}}
                                </span>
                                <span>
                                    {{-- <img src="{{ asset( auth()->user()->image) }}" alt="{{auth()->user()->name}}" class="rounded-circle w-32 mr-2"> --}}
                                </span>
                            </a>
                            <div class="dropdown-menu ">
                                
                                <a class="dropdown-item" href="profile.html"><i class="mdi mdi-account-outline mr-2"></i><span>My profile</span></a>
                                <a class="dropdown-item" href="#"><i class="mdi mdi-settings mr-2"></i><span>Settings</span></a>
                                <a class="dropdown-item" href="#"><i class=" mdi mdi-message-outline mr-2"></i> <span>Mails</span></a>
                                <a class="dropdown-item" href="#"><i class=" mdi mdi-account-multiple-outline mr-2"></i> <span>Friends</span></a>
                                <a class="dropdown-item" href="#"><i class="fe fe-calendar mr-2"></i> <span>Activity</span></a>
                                <a class="dropdown-item" href="#"><i class="mdi mdi-compass-outline mr-2"></i> <span>Support</span></a>
                               
                                {{-- <a class="dropdown-item" href="{{ route('web.auth.logout') }}"><i class="mdi  mdi-logout-variant mr-2"></i> <span>{{trans('logout')}}</span></a> --}}
                            </div>
                        </li>
                    </ul>
                </nav>
                <!--nav closed-->

                <!--aside open-->

            @yield('sidebar', View::make('admin.sidebar'))
            <!--aside closed-->

                @yield('content')

                <!--Footer-->
                <footer class="main-footer">
                    <div class="text-center">
                        Copyright &copy;Haleel 2020</a>
                    </div>
                </footer>
                <!--/Footer-->

                <!-- Popupchat open-->
                <div class="popup-box chat-popup" id="qnimate">
                    <div class="popup-head">
                        <div class="popup-head-left pull-left"><img src="{{ url('assets/img/avatar/avatar-3.jpeg') }}" alt="iamgurdeeposahan" class="mr-2"> Alica Nestle</div>
                        <div class="popup-head-right pull-right">
                            <div class="btn-group">
                                <button class="chat-header-button" data-toggle="dropdown" type="button" aria-expanded="false">
                                    <i class="glyphicon glyphicon-cog"></i> </button>
                                <ul role="menu" class="dropdown-menu dropdown-menu-right">
                                    <li><a href="#">Media</a></li>
                                    <li><a href="#">Block</a></li>
                                    <li><a href="#">Clear Chat</a></li>
                                    <li><a href="#">Email Chat</a></li>
                                </ul>
                            </div>
                            <button data-widget="remove" id="removeClass" class="chat-header-button pull-right" type="button"><i class="glyphicon glyphicon-off"></i></button>
                        </div>
                    </div>
                    <div class="popup-messages">
                        <div class="direct-chat-messages">
                            <div class="chat-box-single-line">
                                <abbr class="timestamp">December 15th, 2018</abbr>
                            </div>
                            <div class="direct-chat-msg">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name float-left">Alica Nestle</span>
                                    <span class="direct-chat-timestamp float-right">7:40 Am</span>
                                </div>
                                <img class="direct-chat-img" src="{{ url('assets/img/avatar/avatar-3.jpeg') }}" alt="message user image">
                                <div class="direct-chat-text">
                                    Hello. How are you today?
                                </div>
                            </div>
                            <div class="direct-chat-msg right">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name float-right">Roberts</span>
                                    <span class="direct-chat-timestamp float-left">8:05 Am</span>
                                </div>
                                <img class="direct-chat-img" src="{{ url('assets/img/avatar/avatar-2.jpeg') }}" alt="message user image">
                                <div class="direct-chat-text">
                                    I'm fine. Thanks for asking!
                                </div>
                            </div>
                            <div class="chat-box-single-line  mb-3">
                                <abbr class="timestamp">December 14th, 2018</abbr>
                            </div>
                            <div class="direct-chat-msg doted-border">
                                <div class="direct-chat-info clearfix">
                                    <span class="direct-chat-name float-left">Alica Nestle</span>
                                    <span class="direct-chat-timestamp float-right">6:20 Am</span>
                                </div>
                                <img alt="iamgurdeeposahan" src="{{ url('assets/img/avatar/avatar-3.jpeg') }}" class="direct-chat-img"><!-- /.direct-chat-img -->
                                <div class="direct-chat-text">
                                    Hey bro, how’s everything going ?
                                </div>
                                <div class="direct-chat-msg right">
                                    <div class="direct-chat-info clearfix">
                                        <span class="direct-chat-name float-right">Roberts</span>
                                        <span class="direct-chat-timestamp float-left">7:05 Am</span>
                                    </div>
                                    <img class="direct-chat-img" src="{{ url('assets/img/avatar/avatar-2.jpeg') }}" alt="message user image">
                                    <div class="direct-chat-text">
                                        Nothing Much!
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="popup-messages-footer">
                        <textarea id="status_message" placeholder="Type a message..." rows="10" cols="40" name="message"></textarea>
                        <div class="btn-footer">
                            <button class="bg_none"><i class="glyphicon glyphicon-film"></i> </button>
                            <button class="bg_none"><i class="glyphicon glyphicon-camera"></i> </button>
                            <button class="bg_none"><i class="glyphicon glyphicon-paperclip"></i> </button>
                            <button class="bg_none pull-right"><i class="glyphicon glyphicon-thumbs-up"></i> </button>
                        </div>
                    </div>
                </div>
                <!-- Popupchat closed -->

            </div>
        </div>
        <!--app closed-->

        <!-- Back to top -->
        <a href="#top" id="back-to-top" ><i class="fa fa-angle-up"></i></a>

        <!--Jquery.min js-->
        <script src="{{ url('assets/js/admin.app.js') }}"></script>

        <script src="{{ url('assets/js/googlemap.js') }}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAndFqevHboVWDN156vJqXk1Y1-D7QR7BE&libraries=places&callback=initAutocomplete" async defer></script>
        
        @yield('scripts')
    </body>
</html>

resources/views/admin/sidebar.blade.php
<aside class="app-sidebar">
    <div class="app-sidebar__user">
        <div class="dropdown user-pro-body text-center">
            <div class="nav-link pl-1 pr-1 leading-none ">
                {{-- <img src="{{ asset( auth()->user()->image) }}" alt="user-img" --}}
                     {{-- class="avatar-xl rounded-circle mb-1"> --}}
                <span class="pulse bg-success" aria-hidden="true"></span>
            </div>
            <div class="user-info">
                {{-- <h6 class=" mb-1 text-dark">{{auth()->user()->user_name}}</h6> --}}
                {{-- <span class="text-muted app-sidebar__user-nam e text-sm">{{ auth()->user()->email }} </span> --}}
            </div>
        </div>
    </div>
    <ul class="side-menu">
        <li>
            <a class="slide-item" href="#">
                <span><i class="side-menu__icon fa fa-area-chart"></i>{{ trans('dashboard') }}</span>

            </a>
        </li>
        
        <li>
            <a class="slide-item" href="{{ route('admin.branches.index') }}">
                <span><i class="side-menu__icon fa fa-shopping-cart"></i>{{ trans('branches') }}</span>
            </a>
        </li>
        <li>
            <a class="slide-item" href="{{ route('admin.products.index') }}">
                <span><i class="side-menu__icon fa fa-shopping-cart"></i>{{ trans('products') }}</span>
            </a>
        </li>

        <li>
            <a class="slide-item" href="{{ route('admin.orders.index') }}">
                <span><i class="side-menu__icon fa fa fa-money"></i>{{ trans('orders') }}</span>
            </a>
        </li>

        <li>
            <a class="slide-item" href="{{ route('admin.payments.index') }}">
                <span><i class="side-menu__icon fa fa fa-money"></i>{{ trans('payments') }}</span>
            </a>
        </li>
        <li>
            <a class="slide-item" href="{{ route('admin.users.index') }}">
                <span><i class="side-menu__icon fa fa-user"></i>{{ trans('users') }}</span>
            </a>
        </li>
    </ul>
</aside>