routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Contracts\Auth\Factory as AuthFactory;
use Illuminate\Support\Facades\Hash;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(
    ['prefix' => LaravelLocalization::setLocale(),
     'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {
        Route::get('/', function()
        {
            return view('welcome');
        });
        Route::prefix('/admin')->attribute('namespace', 'Admin')->group(function(){
            Route::get('/', 'HomeController@index')->name('admin.home.index');
            Route::resource('products', 'ProductController', ['as' => 'admin']);    
            Route::resource('orders', 'OrdersController', ['as' => 'admin']);    
            Route::resource('branches', 'BranchesController', ['as' => 'admin']);    
            Route::resource('users', 'UserController', ['as' => 'admin']);    
            Route::resource('payments', 'PaymentsController', ['as' => 'admin']);    
        });
        Route::get('/test' , function(){
            $credentials  = ['phone'=>'+1-386-764-6166','password'=>'123456789'];
           // dd(auth('api'));
            $user = auth('api')->attempt($credentials);
            dd($user);
        });
        
        

});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;

class Product extends Model implements TranslatableContract
{
    use Translatable ;
    public $translatedAttributes = ['name', 'description'];
    protected $hidden = ['translations'];
    protected $appends = array('name', 'description');


}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Repositories\BranchRepository ;
use App\Constants\OrderStatus;
use App\Constants\VendorTypes;
use App\Constants\PaymentTypes;
use App\Http\Controllers\Controller ;
use App\Http\Requests\Admin\OrderRequest;
use App\Http\Services\OrderService;
use App\Models\Order;
use App\Models\Branch;
use App\Models\User;
use App\Repositories\OrderRepository;
use View;
use Symfony\Component\HttpFoundation\Request;

class OrdersController extends Controller
{
    protected $orderService;
    protected $orderRepository;
    protected $branchRepository;

    public function __construct(OrderService $orderService, OrderRepository $orderRepository
                               , BranchRepository  $branchRepository
        )
    {
        $this->orderService = $orderService;
        $this->orderRepository = $orderRepository;
        $this->branchRepository = $branchRepository;
    }

    public function index()
    {
        $status = OrderStatus::getList();
        $paymentTypes = PaymentTypes::getList();
        $branchs = Branch::whereActive(1)->get();
        $ordersCount = $this->orderRepository->search()->count();
        $list = $this->orderRepository->search(request())->paginate(10);
        $list->appends(request()->all());

        return View::make('admin.orders.index', compact('branchs','list', 'status','ordersCount' , 'paymentTypes'));
    }

    public function create()
    {
        $branchs = Branch::all();

        return View::make('admin.orders.new', ['branchs'=>$branchs]);
    }

    public function store(OrderRequest $request)
    {
        $this->orderService->fillFromRequest($request);

        return redirect(route('admin.orders.index'))->with('success', trans('order_added_successfully'));
    }

    public function edit(Order $order)
    {
        $users = User::all();

        $addresses = Address::where('user_id', $order->user_id)->get();

        return View::make('admin.orders.edit', ['order' => $order,'users'=>$users, 'addresses'=>$addresses]);
    }

    public function update(OrderRequest $request, Order $order)
    {
        $this->orderService->fillFromRequest($request, $order);

        return redirect(route('admin.orders.index'))->with('success', trans('order_updated_successfully'));
    }

    public function products(Order $order)
    {
        $list = $order->products;

        return View::make('admin.orders.products.index', ['list' => $list,'order'=>$order]);
    }

    public function addProduct(Order $order)
    {
        $branchProducts = BranchProduct::all();

        return View::make('admin.orders.products.new', ['order' => $order, 'branchProducts' => $branchProducts]);
    }

    public function storeProduct(OrderProductsRequest $request, Order $order)
    {
        $this->orderService->fillOrderProductsFromRequest($request);

        return redirect(route('admin.order.products', ['order' => $order->id]))->with('success', trans('order_product_added_successfully'));
    }

    public function editProduct(OrderProduct $orderProduct)
    {
        $branchProducts = BranchProduct::all();

        return View::make('admin.orders.products.edit', ['orderProduct' => $orderProduct,'branchProducts'=>$branchProducts]);
    }

    public function updateProduct(OrderProductsRequest $request, OrderProduct $orderProduct)
    {
        $this->orderService->fillOrderProductsFromRequest($request, $orderProduct);

        return redirect(route('admin.order.products', ['order' => $orderProduct->order_id]))->with('success', trans('order_product_updated_successfully'));
    }

    public function destroyProduct(OrderProduct $orderProduct)
    {
        $orderProduct->delete();

        $this->orderService->setOrderTotalCost($orderProduct);

        return redirect()->back()->with('success', trans('order_product_deleted_successfully'));
    }

    public function export()
    {
        return $this->orderService->export();
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller ;
use App\Constants\BranchTypes;
use App\Http\Requests\Admin\ProductRequest;
use App\Http\Services\ProductService;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Unit;
use App\Models\Category;
use App\Repositories\ProductRepository;
use App\Repositories\BranchRepository;
use View;

class ProductController extends Controller
{

    private $productRepository;
    private $branchRepository;

    public function __construct(ProductService $productService, ProductRepository $productRepository
                                , BranchRepository $branchRepository)
    {
        $this->productService = $productService;
        $this->productRepository = $productRepository;
        $this->branchRepository = $branchRepository;
    }

    public function index()
    {
        $list = $this->productRepository->search(request())->paginate(10);
        $list->appends(request()->all());
        $count = $this->productRepository->search(request())->count();

        return View::make("admin.products.index", compact("list", "count"));
    }

    public function create()
    {
        return View::make("admin.products.create", compact("branchs"));
    }

    public function store(ProductRequest $request)
    {
        $product = $this->productService->fillFromRequest($request);
        return redirect(route("admin.products.index"))->with('success', trans('item_added_successfully'));
    }

    public function edit(Product $product)
    {
        return View::make("admin.products.edit", compact("product", 'units', 'categories'));
    }

    public function update(ProductRequest $request, Product $product)
    {
        $product = $this->productService->fillFromRequest($request, $product);
        return redirect(route("admin.products.index"))->with('success', trans('item_updated_successfully'));
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return back()->with('success', trans('item_deleted_successfully'));
    }

    public function deleteImage(Product $product, ProductImage $productImage)
    {
        $result = $this->productService->deleteImage($product, $productImage);

        if ($result) {
            return back()->with('success', trans('item_deleted_successfully'));
        }

        return back()->with('error', trans('error_not_complete'));
    }

}

resources/views/admin/orders/products/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="app-content">
        <section class="section">

            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('order_products')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.order.products.index', ['order' => $orderProduct->order_id]) }}" class="text-light-color">{{trans('order_products')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('update_order_products')}} #{{ $orderProduct->id }}</li>
                </ol>
            </div>
            <!--page-header closed-->

            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{trans('update_order_products')}}</h4>
                            </div>
                            <div class="card-body">
                                @include('admin.errors')
                                <form action="{{ route('admin.order.products.update', ['order'=>$orderProduct->order_id,'orderProduct' => $orderProduct]) }}" method="post">
                                    @method("PUT")
                                    @csrf
                                    <input type="hidden" name="order_id" value="{{$orderProduct->order_id}}">
                                    <div class="form-group col-md-4">
                                        <div class="form-group overflow-hidden">
                                            <label>{{trans('products')}}</label>
                                            <select name="branch_product_id"  class="form-control select2 w-100" id="branch_product_id" >
                                            <option value="">{{ trans('select_product') }}</option>
                                                @foreach($branchProducts as $branchProduct)
                                                    <option value="{{ $branchProduct->id }}" {{ $branchProduct->id == old( 'branch_product_id', $orderProduct->branch_product_id) ? "selected":null }}>{{ $branchProduct->product->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <input type="hidden" value="{{ old('price',$orderProduct->price) }}" name="price" id="price" >

                                    <div class="form-group col-md-4">
                                        <label for="quantity">{{ trans('quantity') }}</label>
                                        <input type="number" min="1" class="form-control" value="{{ old('quantity',$orderProduct->quantity) }}" name="quantity" id="quantity" >
                                    </div>

                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/admin/orders/products/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="app-content">
        <section class="section">

            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('order_products')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.orders.index') }}" class="text-light-color">{{trans('orders')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('order_products')}}</li>
                </ol>
            </div>
            <!--page-header closed-->

            <div class="section-body">
                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                @can('create' , OrderProduct::class)
                                    <span class="table-add float-right">
                                        <a href="{{ route('admin.order.products.create' , ['order' => $order->id]) }}" class="btn btn-icon"><i class="fa fa-plus fa-1x" aria-hidden="true"></i></a>
                                    </span>
                                @endcan
                                <h4>{{trans('order_products_list')}}</h4>
                            </div>

                            <div class="card-body">
                                @if(session()->has('success'))
                                    <div class="alert alert-success alert-has-icon alert-dismissible show fade">
                                        <div class="alert-icon"><i class="ion ion-ios-lightbulb-outline"></i></div>
                                        <div class="alert-body">
                                            <button class="close" data-dismiss="alert">
                                                <span>×</span>
                                            </button>
                                            <div class="alert-title">{{trans('success')}}</div>
                                            {{ session('success') }}
                                        </div>
                                    </div>
                                @endif

                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover mb-0 text-nowrap">
                                        <thead>
                                            <tr>
                                                <th style="width: 1px">#</th>
                                                <th>{{trans('product')}}</th>
                                                <th>{{trans('price')}}</th>
                                                <th>{{trans('quantity')}}</th>
                                                <th style="width: 1px">{{trans('actions')}}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($list as $product)        
                                            @php
                                                $orderProduct = \App\Models\OrderProduct::find($product->pivot->id);
                                            @endphp
                                            <tr>
                                                <td>{{ $product->pivot->id }}</td>
                                                <td>{{ $product->product->name }}</td>
                                                <td>{{ $product->pivot->price }} </td>
                                                <td>{{ $product->pivot->quantity }}</td>
                                                <td>
                                                    <div class="btn-group dropdown">
                                                        <button type="button" class="btn btn-sm btn-info m-b-5 m-t-5 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <i class="fa-cog fa"></i>
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            @can('update', $orderProduct)
                                                                <a class="dropdown-item has-icon" href="{{ route('admin.order.products.edit', ['order'=>$order->id ,'orderProduct' => $product->pivot->id]) }}"><i class="fa fa-edit"></i> {{trans('edit')}}</a>
                                                            @endcan
                                                        
                                                            @can('delete',$orderProduct)
                                                                <button type="button" class="dropdown-item has-icon" data-toggle="modal" data-target="#delete_model_{{ $product->pivot->id }}">
                                                                <i class="fa fa-trash"></i> {{trans('remove')}}
                                                            </button>
                                                            @endcan
                                                        </div>
                                                    </div>

                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="d-flex justify-content-center">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        @foreach ($list as $product)
        <!-- Message Modal -->
            <div class="modal fade" id="delete_model_{{ $product->pivot->id }}" tabindex="-1" role="dialog"  aria-hidden="true">
                
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="example-Modal3">{{ trans('delete') }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form action="{{ route('admin.order.products.destroy', ['order' =>$order->id ,'orderProduct' => $product->pivot->id]) }}" method="Post" >
                            @method('DELETE')
                            @csrf
                            <div class="modal-body">

                            {{ trans('delete_confirmation_message') }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-success" data-dismiss="modal">{{ trans('close') }}</button>
                                <button type="submit" class="btn btn-primary">{{ trans('delete') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Message Modal closed -->
        @endforeach

    </div>
@stop

resources/views/admin/orders/products/new.blade.php
@extends('admin.layout')

@section('content')
    <div class="app-content">
        <section class="section">

            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('order_products')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.order.products.index', ['order' => $order->id]) }}" class="text-light-color">{{trans('order_products')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('new')}}</li>
                </ol>
            </div>
            <!--page-header closed-->

            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{trans('new_order_product')}}</h4>
                            </div>
                            <div class="card-body">
                                @include('admin.errors')
                                <form action="{{ route('admin.order.products.store',['order'=>$order->id]) }}" method="post">
                                    @csrf
                                    <input type="hidden" name="order_id" value="{{$order->id}}">
                                    <div class="form-group col-md-4">
                                        <div class="form-group overflow-hidden">
                                            <label>{{trans('products')}}</label>
                                            <select name="branch_product_id"  class="form-control select2 w-100" id="branch_product_id" >
                                            <option value="">{{ trans('select_product') }}</option>
                                                @foreach($branchProducts as $branchProduct)
                                                    <option value="{{ $branchProduct->id }}" {{ old("branchProduct_id") == $branchProduct->id ? "selected":null }}>{{ $branchProduct->product->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="quantity">{{ trans('quantity') }}</label>
                                        <input type="number" min="1" class="form-control" value="{{ old('quantity') }}" name="quantity" id="quantity" >
                                    </div>
                                    
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection