routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Contracts\Auth\Factory as AuthFactory;
use Illuminate\Support\Facades\Hash;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(
    ['prefix' => LaravelLocalization::setLocale(),
     'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {
        Route::get('/', function()
        {
            return view('welcome');
        });
        Route::prefix('/admin')->attribute('namespace', 'Admin')->group(function(){
            Route::get('/', 'HomeController@index')->name('admin.home.index');
            Route::resource('products', 'ProductController', ['as' => 'admin']);    
            Route::resource('orders', 'OrdersController', ['as' => 'admin']);    
            Route::resource('branches', 'BranchesController', ['as' => 'admin']);    
            Route::resource('users', 'UserController', ['as' => 'admin']);    
            Route::resource('payments', 'PaymentsController', ['as' => 'admin']);    
        });
        Route::get('/test' , function(){
            $credentials  = ['phone'=>'+1-386-764-6166','password'=>'123456789'];
           // dd(auth('api'));
            $user = auth('api')->attempt($credentials);
            dd($user);
        });
        
        

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    protected $fillable = [
        'name', 'type', 'email', 'password', 'address', 'phone'
    ];
    public $Attributes = [
        'notification ' => 1
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
    public function setPasswordAttribute($pass)
    {
        $this->attributes['password'] = \Hash::make($pass);
    }

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    /**
     * Set Relation with fcm token
     *
     * @return HasOne
     */
    public function fcm()
    {

        return $this->hasOne(FcmToken::class);
    }
    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Constants\ClassTypes;
use App\Constants\UserTypes;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Services\UploaderService;
use App\Http\Services\UserService;
use App\Models\User;
use App\Models\Vendor;
use App\Models\Company;
use App\Repositories\UserRepository;
use App\Repositories\BranchRepository;
use View;
use File;
use App\Http\Controllers\Controller ;

class UserController extends Controller
{
    protected $userService;
    public $userRepository;
    public $branchRepository;
    public $uploaderService;

    public function __construct(UserService $userService, UserRepository $userRepository
                               , UploaderService $uploaderService, BranchRepository $branchRepository )
    {
        // $this->authorizeResource(User::class, "user");
        $this->userService = $userService;
        $this->branchRepository = $branchRepository;
        $this->userRepository = $userRepository;
        $this->uploaderService = $uploaderService;
    }

    public function index()
    {
        // $this->authorize("index", User::class);
        $list = $this->userRepository->search(request())->paginate(10);
        $list->appends(request()->all());
        $count = $this->userRepository->search(request())->count();
        $types = UserTypes::getList();

        return View::make('admin.users.index', ['list' => $list, 'count' => $count, 'types' => $types]);
    }

    public function create()
    {
        $branchs = $this->branchRepository->search()->get();
        return View::make('admin.users.create', compact('branchs'));
    }

    public function store(UserRequest $request)
    {
        $this->userService->fillFromRequest($request);
        return redirect(route('admin.users.index'))->with('success', trans('item_added_successfully'));
    }

    public function edit(User $user)
    {
        return View::make('admin.users.edit', compact('user'));
    }

    public function update(UserRequest $request, User $user)
    {
        $this->userService->fillFromRequest($request, $user);
        return redirect(route('admin.users.index'))->with('success', trans('item_updated_successfully'));
    }

    public function destroy(User $user)
    {
        $this->uploaderService->deleteFile($user->image);
        $user->delete();

        return redirect()->back()->with('success', 'Item Deleted Successfully');
    }

}

resources/views/admin/users/create.blade.php
@extends('admin.layout')

@section('content')
<?php
use \App\Constants\UserTypes;
?>
    <div class="app-content">
        <section class="section">

            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('users')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}"
                                                   class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}"
                                                   class="text-light-color">{{trans('users')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('new')}}</li>
                </ol>
            </div>
            <!--page-header closed-->

            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{trans('new_user')}}</h4>
                            </div>
                            <div class="card-body">
                                @include('admin.errors')
                                <form action="{{ route('admin.users.store') }}" method="POST"
                                      enctype="multipart/form-data">
                                    @csrf

                                    <div class=" row">

                                        <div class="form-group col-md-6">
                                            <label for="first_name">{{trans('first_name')}}</label>
                                            <input type="text" class="form-control" name="first_name" id="first_name" value="{{ old('first_name') }}">
                                        </div>

                                        <div class="form-group col-md-6">
                                            <label for="last_name">{{trans('last_name')}}</label>
                                            <input type="text" class="form-control" name="last_name" id="last_name" value="{{ old('last_name') }}">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6">
                                            <label for="email">{{trans('email')}}</label>
                                            <input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}">
                                        </div>
    
                                        <div class="form-group col-md-6">
                                            <label for="phone">{{trans('phone')}}</label>
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-phone"></i>
                                                </div>
                                                <input type="text" class="form-control" name="phone" id="phone"
                                                value="{{ old('phone') }}" data-inputmask='"mask": "99999999999"' data-mask>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6">
                                            <label for="password">{{trans('password')}}</label>
                                            <input type="password" class="form-control" name="password" id="password">
                                        </div>

                                        <div class="form-group col-md-6">
                                            <label for="password_confirmation">{{trans('password_confirmation')}}</label>
                                            <input type="password" class="form-control" name="password_confirmation" id="password_confirmation">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="form-group col-md-6">
                                            <div class="form-group overflow-hidden">
                                                <label for="types">{{trans('user_type')}}</label>
                                                <select name="type" class="form-control select2 w-100" id="types">
                                                    <option value="">{{ trans('select_user_type') }}</option>
                                                    @foreach(UserTypes::getList() as $key => $value)
                                                        <option value="{{ $key }}" {{ old('type') == $key ? 'selected': ''}} >{{ $value }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group col-md-6 " style="margin-top:25px;">
                                            <label class="custom-switch">
                                                <input type="checkbox" name="active" value="1" checked class="custom-switch-input">
                                                    <span class="custom-switch-indicator"></span>
                                                    <span class="custom-switch-description">{{trans('active')}}</span>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-6">
                                            <label class="custom-switch"> {{ trans('image') }}
                                                <input type="file"  style="display:none;" onchange="readURL(this,'upload_img');" name="image" class="image" >
                                                <img id="upload_img" src="{{ asset('assets/img/add_img.jpg')}}">
                                            </label>
                                        </div> 
                                        <div class="col-md-3"></div>

                                        
                                    </div>

                                    <div class="form-group col-md-12 row">
                                        <div class="form-group col-md-3">
                                            <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5">
                                                <i class="fa fa-save"></i> {{trans('save')}}
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </section>
    </div>
@stop

@section('scripts')
    <script >

        $('#types').on('change', function () {
            $('#vendor').hide();
            $('#vendor').val(null);

        
           
        });
    </script>

@stop

resources/views/admin/users/edit.blade.php
@extends('admin.layout')

@section('content')
<?php

use \App\Constants\UserTypes;
?>
<div class="app-content">
    <section class="section">

        <!--page-header open-->
        <div class="page-header">
            <h4 class="page-title">{{trans('users')}}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}" class="text-light-color">{{trans('users')}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{trans('update_user')}}</li>
            </ol>
        </div>
        <!--page-header closed-->

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{trans('new_user')}}</h4>
                        </div>
                        <div class="card-body">
                            @include('admin.errors')
                            <form action="{{ route('admin.users.update', ['user' => $user]) }}" method="Post" enctype="multipart/form-data" autocomplete="off" >
                                @method('PUT')
                                @csrf
                                <input type="hidden" name="id" value="{{ $user->id}}" />


                                <div class="form-group col-md-12 row">
                                    <div class="form-group col-md-6">
                                        <label for="first_name">{{trans('first_name')}}</label>
                                        <input type="text" class="form-control" name="first_name" id="first_name" value="{{ !(old('first_name'))? $user->first_name : old('first_name' )}}" >
                                    </div>

                                    <div class="form-group col-md-6">
                                        <label for="last_name">{{trans('last_name')}}</label>
                                        <input type="text" class="form-control" name="last_name" id="last_name" value="{{ !(old('last_name'))? $user->last_name : old('last_name') }}" >
                                    </div>
                                </div>

                                <div class="form-group col-md-12 row">

                                    <div class="form-group col-md-6">
                                        <label for="email">{{trans('email')}}</label>
                                        <input type="email" class="form-control" name="email" id="email"  value="{{ !(old('email'))? $user->email : old('email') }}" >
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="phone">{{trans('phone')}}</label>
                                        <div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-phone"></i>
                                            </div>
                                            <input type="text" class="form-control"  name="phone" id="phone"  value="{{ !(old('phone'))? $user->phone : old('phone') }}" data-inputmask='"mask": "99999999999"' data-mask >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group col-md-12 row">

                                    <div class="form-group col-md-6">
                                        <label for="password">{{trans('password')}}</label>
                                        <input type="password" class="form-control" name="password" id="password"  >
                                    </div>

                                    <div class="form-group col-md-6">
                                        <label for="password_confirmation">{{trans('password_confirmation')}}</label>
                                        <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" >
                                    </div>
                                </div>
                                <div class="form-group col-md-12 row">
                                    <div class="form-group col-md-6">
                                        <div class="form-group overflow-hidden">
                                            <label for="types">{{trans('user_type')}}</label>
                                            <select name="type"  class="form-control select2 w-100" id="types" >
                                                <option value="">{{ trans('select_user_type') }}</option>
                                                @foreach(UserTypes::getList() as $key => $value)
                                                <option value="{{ $key }}" {{ $user->type == $key ? "selected":null }}> {{ $value }} </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                
                                    <div class="form-group col-md-6" style="margin-top:25px;">
                                        <label class="custom-switch">
                                            <input type="checkbox" name="active" value="1" {{ $user->active ? 'checked' : '' }} class="custom-switch-input">
                                            <span class="custom-switch-indicator"></span>
                                            <span class="custom-switch-description">{{trans('active')}}</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group col-md-12 row">
                                    <div class="col-md-3"></div>
                                    
                                    <div class="form-group col-md-6">
                                        <label class="custom-switch"> {{ trans('choose_profile_picture') }}
                                            <input type="file"  style="display:none;" onchange="readURL(this,'upload_img');" name="image" class="image" >
                                            <img id="upload_img" src="{{ asset( $user->image )}}">
                                        </label>
                                    </div>
                                </div>
                                    <div class="col-md-3"></div>
                                </div>

                                
                                
                                <div class="form-group col-md-12 row">
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>

                </div>

            </div>
        </div>

    </section>
</div>
@stop
@section('scripts')
<script>


</script>
@stop

resources/views/admin/users/groups.blade.php
@extends('admin.layout')

@section('content')
<?php
$lang = app()->getLocale();
?>

<div class="app-content">
    <section class="section">

        <!--page-header open-->
        <div class="page-header">
            <h4 class="page-title">{{trans('manage_groups')}}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}" class="text-light-color">{{trans('users')}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{trans('manage_groups')}}</li>
            </ol>
        </div>
        <!--page-header closed-->
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{trans('manage_groups')}}</h4>
                        </div>
                        <div class="card-body">

                            @if(session()->has('success'))
                            <div class="alert alert-success alert-has-icon alert-dismissible show fade">
                                <div class="alert-icon"><i class="ion ion-ios-lightbulb-outline"></i></div>
                                <div class="alert-body">
                                    <button class="close" data-dismiss="alert">
                                        <span>×</span>
                                    </button>
                                    <div class="alert-title">{{trans('success')}}</div>
                                    {{ session('success') }}
                                </div>
                            </div>
                            @endif

                            @include('admin.errors')
                            <form action="{{ route('admin.users.groups.store', ['user' => $user]) }}" method="Post" enctype="multipart/form-data" autocomplete="off" >
                                @method('POST')
                                @csrf

                                <div class="form-group col-md-12 row">
                                    @foreach ($groups as $group)
                                    <div class="form-group mb-0 col-md-4">

                                        <label>
                                            <input type="checkbox" name="groups[]"  value="{{$group->id}}"  {{ ($user->groups->contains('id', $group->id)) ? 'checked' : '' }} >
                                            {{$group->translate($lang)->name}}
                                        </label>

                                    </div>
                                    @endforeach

                                </div>

                                <div class="form-group col-md-12 row">
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5">
                                            <i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop