routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Contracts\Auth\Factory as AuthFactory;
use Illuminate\Support\Facades\Hash;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(
    ['prefix' => LaravelLocalization::setLocale(),
     'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {
        Route::get('/', function()
        {
            return view('welcome');
        });
        Route::prefix('/admin')->attribute('namespace', 'Admin')->group(function(){
            Route::get('/', 'HomeController@index')->name('admin.home.index');
            Route::resource('products', 'ProductController', ['as' => 'admin']);    
            Route::resource('orders', 'OrdersController', ['as' => 'admin']);    
            Route::resource('branches', 'BranchesController', ['as' => 'admin']);    
            Route::resource('users', 'UserController', ['as' => 'admin']);    
            Route::resource('payments', 'PaymentsController', ['as' => 'admin']);    
        });
        Route::get('/test' , function(){
            $credentials  = ['phone'=>'+1-386-764-6166','password'=>'123456789'];
           // dd(auth('api'));
            $user = auth('api')->attempt($credentials);
            dd($user);
        });
        
        

});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Repositories\BranchRepository ;
use App\Constants\OrderStatus;
use App\Constants\VendorTypes;
use App\Constants\PaymentTypes;
use App\Http\Controllers\Controller ;
use App\Http\Requests\Admin\OrderRequest;
use App\Http\Services\OrderService;
use App\Models\Order;
use App\Models\Branch;
use App\Models\User;
use App\Repositories\OrderRepository;
use View;
use Symfony\Component\HttpFoundation\Request;

class OrdersController extends Controller
{
    protected $orderService;
    protected $orderRepository;
    protected $branchRepository;

    public function __construct(OrderService $orderService, OrderRepository $orderRepository
                               , BranchRepository  $branchRepository
        )
    {
        $this->orderService = $orderService;
        $this->orderRepository = $orderRepository;
        $this->branchRepository = $branchRepository;
    }

    public function index()
    {
        $status = OrderStatus::getList();
        $paymentTypes = PaymentTypes::getList();
        $branchs = Branch::whereActive(1)->get();
        $ordersCount = $this->orderRepository->search()->count();
        $list = $this->orderRepository->search(request())->paginate(10);
        $list->appends(request()->all());

        return View::make('admin.orders.index', compact('branchs','list', 'status','ordersCount' , 'paymentTypes'));
    }

    public function create()
    {
        $branchs = Branch::all();

        return View::make('admin.orders.new', ['branchs'=>$branchs]);
    }

    public function store(OrderRequest $request)
    {
        $this->orderService->fillFromRequest($request);

        return redirect(route('admin.orders.index'))->with('success', trans('order_added_successfully'));
    }

    public function edit(Order $order)
    {
        $users = User::all();

        $addresses = Address::where('user_id', $order->user_id)->get();

        return View::make('admin.orders.edit', ['order' => $order,'users'=>$users, 'addresses'=>$addresses]);
    }

    public function update(OrderRequest $request, Order $order)
    {
        $this->orderService->fillFromRequest($request, $order);

        return redirect(route('admin.orders.index'))->with('success', trans('order_updated_successfully'));
    }

    public function products(Order $order)
    {
        $list = $order->products;

        return View::make('admin.orders.products.index', ['list' => $list,'order'=>$order]);
    }

    public function addProduct(Order $order)
    {
        $branchProducts = BranchProduct::all();

        return View::make('admin.orders.products.new', ['order' => $order, 'branchProducts' => $branchProducts]);
    }

    public function storeProduct(OrderProductsRequest $request, Order $order)
    {
        $this->orderService->fillOrderProductsFromRequest($request);

        return redirect(route('admin.order.products', ['order' => $order->id]))->with('success', trans('order_product_added_successfully'));
    }

    public function editProduct(OrderProduct $orderProduct)
    {
        $branchProducts = BranchProduct::all();

        return View::make('admin.orders.products.edit', ['orderProduct' => $orderProduct,'branchProducts'=>$branchProducts]);
    }

    public function updateProduct(OrderProductsRequest $request, OrderProduct $orderProduct)
    {
        $this->orderService->fillOrderProductsFromRequest($request, $orderProduct);

        return redirect(route('admin.order.products', ['order' => $orderProduct->order_id]))->with('success', trans('order_product_updated_successfully'));
    }

    public function destroyProduct(OrderProduct $orderProduct)
    {
        $orderProduct->delete();

        $this->orderService->setOrderTotalCost($orderProduct);

        return redirect()->back()->with('success', trans('order_product_deleted_successfully'));
    }

    public function export()
    {
        return $this->orderService->export();
    }
}

resources/views/admin/orders/edit.blade.php
@extends('admin.layout')

@section('content')
    <?php
        use \App\Constants\OrderStatus;
    ?>
    <div class="app-content">
        <section class="section">

            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('orders')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.orders.index') }}" class="text-light-color">{{trans('orders')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('update_order')}} #{{ $order->id }}</li>
                </ol>
            </div>
            <!--page-header closed-->

            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{trans('update_order')}}</h4>
                            </div>
                            <div class="card-body">
                                @include('admin.errors')
                                <form action="{{ route('admin.orders.update', ['order' => $order]) }}" method="post">
                                    @method("PUT")
                                    @csrf
                                    <div class="form-group col-md-4">
                                        <div class="form-group overflow-hidden">
                                            <label>{{trans('users')}}</label>
                                            <select name="user_id"  class="form-control select2 w-100" id="user_id" >
                                            <option value="">{{ trans('select_user') }}</option>
                                                @foreach($users as $user)
                                                    <option value="{{ $user->id }}" {{ $user->id == old( 'user_id', $order->user_id) ? "selected":null }}>{{ $user->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-4" id="addresses" >
                                        <div class="form-group overflow-hidden">
                                            <label>{{trans('address')}}</label>
                                            <select name="address_id"  class="form-control select2 w-100" id="address_id" >
                                                <option value="">{{ trans('select_address') }}</option>
                                                @foreach($addresses as $address)
                                                    <option value="{{ $address->id }}" {{ $address->id == old( 'address_id', $order->address_id) ? "selected":null }}>{{ $address->location->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-4" id="status" >
                                        <div class="form-group overflow-hidden">
                                            <label>{{trans('status')}}</label>
                                            <select name="status"  class="form-control select2 w-100" id="status" >
                                                <option value="" selected>{{ trans('select_status') }}</option>
                                                @foreach(OrderStatus::getList() as $key => $value)
                                                    <option value="{{ $key }}" {{ $key == old( 'status', $order->status) ? "selected":null }}>{{ $value }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="preferred_delivery_time">{{trans('preferred_delivery_time')}}</label>
                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-clock-o inputIcon"></i>
                                            </div>
                                            <input class="timepicker form-control" type="text" name="preferred_delivery_time" value="{{ old('preferred_delivery_time', $order->preferred_delivery_time) }}">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop
@section('scripts')
    <script>
        $('#user_id').on('change', function() {
            var user =  this.value;
            $.ajax({
                url: '{{ route("api.addresses.index") }}',
                type: 'get',
                data: { _token: '{{ csrf_token() }}', 'user':user},

                success: function(data){
                    $('#addresses').show();
                    var html='<option value ="">{{ trans("select_address") }}</option>';
                    var i;
                    for(i=0;i<data.length;i++){
                        html+=
                            '<option value ="'+data[i].id+'">'+data[i].location.name+'</option>';
                    }
                    $('#address_id').html(html);
                },
                error: function(){
                    alert("error");
                }
            });
        });
    </script>
    <script>
        $(document).ready(function(){
            $('input.timepicker').timepicker({});
            $('.timepicker').timepicker({
                timeFormat: 'h:mm p',
                interval: 60,
                minTime: '10',
                maxTime: '6:00pm',
                defaultTime: '11',
                startTime: '10:00',
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });
        });
    </script>
@endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layout')

@section('content')
<?php
use \App\Constants\OrderStatus;
?>
    <div class="app-content">
        <section class="section">

            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('orders')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('orders')}}</li>
                </ol>
            </div>
            <!--page-header closed-->
            <div class="row">
                <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <form class="form-horizontal" type="get" action="{{ route("admin.orders.index") }}">
                                <div class="form-group row">
                                    <div class="col-md-6">
                                        <select name="status"  class="form-control select2 w-100" id="status" >
                                            <option value="" >{{ trans('select_status') }}</option>
                                            @foreach($status as $key =>$value)
                                                <option value="{{ $key }}" {{ request("status") == $key ? "selected":null }}>{{ $value }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                          
                                    <div class="col-md-6">
                                        <select name="payment_type"  class="form-control select2 w-100" id="payment_type" >
                                            <option value="" >{{ trans('select_payment_type') }}</option>
                                            @foreach($paymentTypes as $key =>$value)
                                                <option value="{{ $key }}" {{ request("payment_type") == $key ? "selected":null }}>{{ $value }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-6 input-group date">
                                        <div class="input-group-addon">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        <input type="text" placeholder="{{ trans('from_date') }}" class="form-control dateFrom" value="{{ request("from_date") }}" name="from_date" readonly >
                                    </div>

                                    <div class="col-md-6 input-group date">
                                        <div class="input-group-addon">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        <input type="text" placeholder="{{ trans('to_date') }}" class="form-control dateTo" value="{{ request("to_date") }}" name="to_date" readonly >
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <select name="banch_id"  class="form-control select2 w-100" id="banch_id" >
                                            <option value="" >{{ trans('select_banch') }}</option>
                                            @foreach($branchs as $branch_id )
                                                <option value="{{ $branch_id }}" {{ request("banch_id") == $branch_id ? "selected":null }}>{{ $branch->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary  mt-1 mb-0">{{ trans("search") }}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <span class="table-add float-right">
                                    <a href="{{ route('admin.orders.create') }}" class="btn btn-icon"><i class="fa fa-plus fa-1x" aria-hidden="true"></i></a>
                                </span>
                                <h4>
                                    {{trans('orders_list')}}
                                    (<small>{{ trans('num_rows') }}</small> <span class="badge badge-success">{{ $ordersCount }}</span>)
                                </h4>

                            </div>

                            <div class="card-body">
                                @if(session()->has('success'))
                                    <div class="alert alert-success alert-has-icon alert-dismissible show fade">
                                        <div class="alert-icon"><i class="ion ion-ios-lightbulb-outline"></i></div>
                                        <div class="alert-body">
                                            <button class="close" data-dismiss="alert">
                                                <span>×</span>
                                            </button>
                                            <div class="alert-title">{{trans('success')}}</div>
                                            {{ session('success') }}
                                        </div>
                                    </div>
                                @endif

                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover mb-0 text-nowrap">
                                        <thead>
                                            <tr>
                                                <th style="width: 1px">#</th>
                                                <th>{{trans('client_name')}}</th>
                                                <th>{{trans('total_cost')}}</th>
                                                <th>{{trans('address')}}</th>
                                                <th>{{trans('status')}}</th>
                                                <th style="width: 1px">{{trans('actions')}}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($list as $order)
                                            <tr>
                                                <td>{{ $order->id }}</td>
                                                <td>{{ $order->user ? $order->user->name : '-' }}</td>
                                                <td>{{ $order->total_price ? $order->total_price  : '-'}}</td>
                                                <td>{{ $order->address->location->name }}</td>
                                                <td>
                                                @foreach(OrderStatus::getList() as $key => $value)

                                                    @if($order->status == $key)
                                                        {{$value}}
                                                    @endif

                                                @endforeach
                                                </td>

                                                <td>
                                                    <div class="btn-group dropdown">
                                                        <button type="button" class="btn btn-sm btn-info m-b-5 m-t-5 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <i class="fa-cog fa"></i>
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            @can('update', $order)
                                                                <a class="dropdown-item has-icon" href="{{ route('admin.orders.edit', ['order' => $order->id]) }}"><i class="fa fa-edit"></i> {{trans('edit')}}</a>
                                                            @endcan
                                                            <a class="dropdown-item has-icon" href="{{ route('admin.order.products.index', ['order' => $order->id]) }}"><i class="fa fa-shopping-cart"></i> {{trans('products')}}</a>
                                                        </div>
                                                    </div>

                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="d-flex justify-content-center">
                                    {{ $list->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/admin/orders/new.blade.php
@extends('admin.layout')

@section('content')
    <div class="app-content">
        <section class="section">
            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('orders')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.orders.index') }}" class="text-light-color">{{trans('orders')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('new')}}</li>
                </ol>
            </div>
            <!--page-header closed-->
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{trans('new_order')}}</h4>
                            </div>
                            <div class="card-body">
                                @include('admin.errors')
                                <form action="{{ route('admin.orders.store') }}" method="post" autocomplete="off">
                                    @csrf
                                    <div class="form-group col-md-4">
                                        <div class="form-group overflow-hidden">
                                            <label>{{trans('branchs')}}</label>
                                            <select name="branch_id"  class="form-control select2 w-100" id="branch_id" >
                                            <option value="">{{ trans('select_branch') }}</option>
                                                @foreach($branchs as $branch)
                                                    <option value="{{ $branch->id }}" {{ old("branch_id") == $branch->id ? "selected":null }}>{{ $branch->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                              
                           
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop
@section('scripts')
<script>
</script>
<script>
    $(document).ready(function(){
        $('input.timepicker').timepicker({});
        $('.timepicker').timepicker({
            timeFormat: 'h:mm p',
            interval: 60,
            minTime: '10',
            maxTime: '6:00pm',
            defaultTime: '11',
            startTime: '10:00',
            dynamic: false,
            dropdown: true,
            scrollbar: true
        });
    });
</script>
@endsection